project 'JGThirdLinkage.xcodeproj'
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

inhibit_all_warnings!

target 'JGThirdLinkage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JGThirdLinkage
  #OC布局
  pod 'Masonry' #,'1.0.2'

  #Swift 布局
  pod 'SnapKit'
  pod 'Reusable'
  
  target 'JGThirdLinkageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JGThirdLinkageUITests' do
    # Pods for testing
  end

end
